Доделана страница start
bmstu-iu9/ptp2022-7-svg-editor pull request #50
Opened 2022-08-22 18:02 UTC by vyydra

Отстайлена страница svg_editor/templates/start.html, css- и js-файлы для которой находятся в папках svg_editor/static/svg_editor/css и /js, соответственно.
Resolves #40

2022-08-22 18:12 UTC, vyydra commented
Забыла добавить, что добавлены фоновые анимации (см. коммит выше) и что файлы для страницы start называются start-styles.css и startDesign.js

2022-08-29 10:51 UTC, Kabane-UN requested changes
Дизайн просто шикарный, но в коде есть косяки. На счет процентов после 0 можешь забить, но остальное критично и это нужно исправить.

2022-08-29 10:51 UTC, Kabane-UN commented on account/static/account/css/main.css
>  .wrapper-email-complete {
.wrapper-email-complete, .wrapper-email-done и .wrapper-email-incomplete. Это ctrl+c ctrl+v.

2022-08-30 13:11 UTC, vyydra commented on svg_editor/static/svg_editor/js/startDesign.js
> +        var template = '<div class="' + classes + '">';
Исправлено

2022-08-30 13:11 UTC, vyydra commented on svg_editor/static/svg_editor/js/startDesign.js
> +            name = $(this).attr("name");
Исправлено

2022-08-30 13:11 UTC, vyydra commented on svg_editor/static/svg_editor/js/startDesign.js
> +            var fileName = '';
Исправлено

2022-08-30 13:11 UTC, vyydra commented on svg_editor/static/svg_editor/js/startDesign.js
> +        event.stopPropagation();
Исправлено

2022-08-30 13:11 UTC, vyydra commented on svg_editor/static/svg_editor/js/startDesign.js
> +    $(".inputfile").each(function () {
Исправлено

2022-08-30 13:14 UTC, vyydra commented on svg_editor/static/svg_editor/js/startDesign.js
> +                fileName = (this.getAttribute("data-multiple-caption") || "").replace("{count}", this.files.length);
Удалила эти строки, так как нет атрибута multiple в элементе input, т.е. проверка на кол-во файлов и все с этим связанное тут вообще не нужна

2022-08-30 13:14 UTC, vyydra commented on account/templates/registration/signup.html
> +<!--{% load static %}-->
Исправлено

2022-08-30 13:23 UTC, vyydra commented on account/static/account/css/main.css
> +    background-image: linear-gradient(to right top, #5b7dab, #708db6, #859ec0, #9aafcb, #afc0d6, #b2c6da, #b6ccde, #bad2e1, #abcedc, #9ccbd5, #8ec7cb, #84c3be);
linear-gradient не поддерживается в старых версиях браузеров. Конечно, это маловероятно, но может, пусть будет на всякий случай...

2022-08-30 13:23 UTC, vyydra commented on account/static/account/css/main.css
> +        background-position: 0% 50%;
Исправлено

2022-08-30 13:23 UTC, vyydra commented on account/static/account/css/main.css
>  .wrapper-email-complete {
Исправлено

2022-08-30 13:53 UTC, Kabane-UN approved these changes
Отлично

2022-08-30 13:55 UTC, merged